### ISSUE TITLE
Investigate 404s

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/n-brightcove-to-capi#1]
1396038663001 UUID http://api.ft.com/content/723bfa01-7b97-3d22-837c-bb108b00b3ee 404
1396290942001 UUID http://api.ft.com/content/3c6fef7c-10dc-3278-8cf3-00b8d90c1bdb 404
1397752647001 UUID http://api.ft.com/content/3d84e107-5c60-3539-8c3f-1f4e5232e2a7 404
1397868607001 UUID http://api.ft.com/content/0694972e-8761-3b6e-9bd0-927d95d0e5c5 404
1398648241001 UUID http://api.ft.com/content/e084d3d4-4c78-3a7d-b51f-f03886b6a1bd 404
1398410731001 UUID http://api.ft.com/content/8eb6bcca-6c5a-3347-a5cc-660159a6a750 404
1399120677001 UUID http://api.ft.com/content/f2d12d2e-fc19-3457-943a-4d17e356d77e 404
1401227153001 UUID http://api.ft.com/content/a351ce8a-d297-39b3-ac16-281a56e96519 404
1400104480001 UUID http://api.ft.com/content/82fad04f-a098-3454-8cf4-7385386e0546 404
1401014979001 UUID http://api.ft.com/content/dc736442-acbd-3cd0-bfaa-e1570116de76 404
1402436454001 UUID http://api.ft.com/content/660e4c68-ac29-3a8c-86b1-e2a457e569c4 404
5146476802001 UUID http://api.ft.com/content/77a7463e-fa38-3683-a4d5-b15f7340833c 404

**Comment by i-like-robots** [comment]
None of these are found in CAPI (when searching by the Brightcove ID)
